### ISSUE TITLE
Room never comes up when I add "proxy" parameter to HBInit

### ISSUE THREAD

**Issue by iwishiknewcoding** [mertushka/haxball.js#15]
As the title suggests, the room never gets created after I add proxy parameter to HBInit as it is mentioned in the docs. I've tried multiple proxy IPs. To be more precise, I don't receive any errors or anything after running `node room.js` there's just a blank output, waiting for something to happen, but nothing does (I've waited for more than 10 mins, or more).

Please note that if I remove just the proxy parameter, then the room comes up online and everything works perfectly. Well done creating this package by the way!

**Comment by iwishiknewcoding** [comment]
After enabling debugging, I'm seeing this in the logs:
```
Error: connect EHOSTUNREACH 0.0.0.80:80 - Local (192.168.68.68:12345)
    at internalConnect (node:net:1060:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1322:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  errno: -65,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '0.0.0.80',
  port: 80
```

**Comment by iwishiknewcoding** [comment]
I added `http://` to the proxy IP, and now I'm getting:
```
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by mertushka** [comment]
Since I don't used a proxy much, I don't know enough about proxies, but we can get help from jakjus about using proxy (cc. @jakjus and https://github.com/mertushka/haxball.js/pull/11), but thank you for providing debugging logs. What kind of proxy server you host on `0.0.0.80:80` by the way?

**Comment by iwishiknewcoding** [comment]
Thanks for the prompt reply. `0.0.0.80:80` was written in the logs incorrectly until I added `http://` to the IP in the room config. I am not hosting any proxy on my side (should I?). I just tried to use 20+ free proxy IPs that I found online.

**Comment by mertushka** [comment]
@jakjus I think I realized we made a mistake;

https://github.com/mertushka/haxball.js/blob/93dc7fdf44944d765466688f025c800afcc76000/src/index.js#L5

https://github.com/mertushka/haxball.js/blob/93dc7fdf44944d765466688f025c800afcc76000/package.json#L22

There should have been `https-proxy-agent` module in package.json but we have `http-proxy-agent`, i think there is possible typo.

For more details:

https://github.com/mertushka/haxball.js/pull/11#pullrequestreview-1085983883

https://github.com/mertushka/haxball.js/pull/11/commits/f1b9d88982b365416f5e74b0783b9e43912ab4e9


Since Haxball using WSS protocol we need HTTPS proxies to establish a connection. I guess I didn't notice because I didn't use a proxy before. This error may be due to this or it may be a situation related to the proxy used. But I think there is a problem with the whole thing I mentioned above.

**Comment by iwishiknewcoding** [comment]
Your suggestion makes a lot of sense, but I'm just wondering, if that is the case, then I should have received `module not found` error before everything else, no?

**Comment by jakjus** [comment]
1.
> Edit 2: I was finally able to start the room with the proxy. I've tried several ones that support https, and one of them worked fine. (I added it in the parameter with `http://` though, because it was still failing with `https://`)
Yeah, it should be `http://`. You can see the example at https://github.com/mertushka/haxball.js#-optional-proxy

2. With the package naming - it should work perfectly fine, because `http-proxy-agent` also installs `https-proxy-agent`. 
```
ubuntu@hb:~/hjstest$ npm i haxball.js
ubuntu@hb:~/hjstest$ ls -d node_modules/http*
node_modules/http-proxy-agent  node_modules/https-proxy-agent
```

3. 
> I am not hosting any proxy on my side (should I?). I just tried to use 20+ free proxy IPs that I found online.
I think you should. But I'm very curious if you encounter reliability problems using free proxies - I'll be glad to know.
The way I do it is, I have several IP's connected to NIC (additional IPs are a paid feature for the most providers). Then, I use Squid to make local proxy - when using `http://0.0.0.0:9050`, the traffic uses first IP (e.g. `53.120.121.53`),  `http://0.0.0.0:9051` is mapped to second IP and so on.

To conclude, I don't see any error within the source code.

**Comment by iwishiknewcoding** [comment]
@jakjus Yeah I encountered reliability issues using free proxies, that's why I decided to go for a paid proxy IP, which resolved the issues and now it's all good. I'm not sure which provider you use, I'm taking a wild guess that it's AWS, just out of curiosity, how does EIP price look like there? I'm paying $0.84/month for my proxy service. Sorry for the offtopic.

Indeed, turns out there's no error within the source code, so I'm closing the issue. Thanks for jumping in both of you.

**Comment by jakjus** [comment]
I remember EIPv4 was free (!) on AWS some time ago. It might have changed now. I'm using OVH, because it has datacenter in Poland. The cost used to be one-time 1,9 EUR~, but I think lately it changed to monthly payments.

I'm happy the problem is solved 😄  Good luck~
