### ISSUE TITLE
Exceptions not outputted in some roomObject functions

### ISSUE THREAD

**Issue by jakjus** [mertushka/haxball.js#19]
Exceptions are not outputted in some roomObject functions.
Example of correct exception output (`room.onRoomLink`):
```
const HaxballJS = require("haxball.js");

HaxballJS.then((HBInit) => {
  const room = HBInit({
    public: false,
    token: "thr1.AAAAAGRnQzBMDYP3KqP38w.-sErfHVd6Pw"
  });
  room.onRoomLink = function (link) {
    console.log(link);
    throw('test')
  };
});
```
Output:
```
/Users/jjuszk/projects/recreate/room.js:13
    throw('test')
    ^
test
```

Example of **incorrect** exception output (`room.onPlayerChat`):
```
const HaxballJS = require("haxball.js");

HaxballJS.then((HBInit) => {
  const room = HBInit({
    public: false,
    token: "thr1.AAAAAGRnQzBMDYP3KqP38w.-sErfHVd6Pw"
  });
  room.onPlayerChat = (player, msg) => {
    throw('test')
  }
  room.onRoomLink = function (link) {
    console.log(link);
  };
});
```

Result:
```
<when typing in the room, getting Disconnected: Connection Closed>
<nothing logged in console>
```

It's also not working correctly for `room.onPlayerJoin`, did not test others, but will do, to find discrepancies.

Env:
```
$ node --version
v18.16.0
```

Tested on node16, node18, node19, node20.

**Comment by mertushka** [comment]
The issue you're facing is related to exception handling in different event handlers of the @basro's code. In some event handlers, exceptions are not being logged as expected, while in others, they are. Let me explain what's happening and how we can address it.

In the first example, we have an event handler called room.onRoomLink, which is a traditional function declaration. Inside this handler, we explicitly throw an exception using the throw statement. Since it's a synchronous operation, the exception is caught and logged by the event loop's error handling mechanism, and we see the output in the console as expected.

However, in the second example, we have an event handler called room.onPlayerChat, which is an arrow function. Arrow functions have an implicit return and behave differently when it comes to exception handling. When we throw an exception inside an arrow function, it doesn't get caught within the function itself. Instead, it propagates up the call stack and may not be caught by the event loop's error handling mechanism. This is why we don't see the exception logged in the console.

To address this issue and ensure consistent exception handling, we need to modify the code. The solution is to explicitly catch the exceptions within each event handler and log them to the console. We can do this by wrapping the code within a try block and catching any exceptions using a catch block.

For example, in the room.onPlayerChat event handler, we can modify the code as follows:

```js
room.onPlayerChat = (player, msg) => {
  try {
    throw new Error('test');
  } catch (error) {
    console.error(error);
  }
};
```

By doing this, any exceptions thrown within the event handler will be caught and logged to the console directly within the handler itself.

**Comment by mertushka** [comment]
> Arrow functions and normal functions have the same behavior regarding exceptions. If you changed the onRoomLink function to an arrow function it would behave the same here.

Yes you are right. Actually both arrow functions and regular functions in JavaScript have the same behavior when it comes to exception handling but I wrote it based on current haxball's error handling. However, closing this as completed.

**Comment by uzayyli** [comment]
Speaking of which, please add error handling to `room.sendAnnouncement`.

If a null or any non-string value is supplied, the function throws an exception which could be easily handled in the core API.

Please handle the following examples so that it doesn't fail the whole room:

`room.sendAnnouncement(3)`
`room.sendAnnouncement(null)`

Thanks
