### ISSUE TITLE
how to add variables and functions in node in the terminal "Part 2"

### ISSUE THREAD

**Issue by Gimenez20** [mertushka/haxball.js#31]
Hi, i saw that on the other post, but for example i want to edit variables and it always says error.

References: https://github.com/mertushka/haxball.js/issues/30

https://github.com/mertushka/haxball.js/issues/16#issuecomment-1425159848

**Comment by Gimenez20** [comment]
For example i want to check my users and it doesnt work

![image](https://github.com/mertushka/haxball.js/assets/55249793/e8792014-6ee9-49ad-8662-d6efb5e0336c)

**Comment by mertushka** [comment]
I guess the error you're encountering is because the eval function executes code in the local scope where it is called. If the variable `usuariosLiga` is not defined in that scope, it will throw a `ReferenceError`.

In your case, it seems `usuariosLiga` is not defined in the scope where eval is being executed. Make sure that `usuariosLiga` is defined and accessible in the same scope.

Here's an example to demonstrate this:

```javascript
// Ensure that usuariosLiga is defined in the same scope
let usuariosLiga = ["user1", "user2", "user3"];

// Then, calling eval should work as expected
eval('console.log(usuariosLiga)');
```
If `usuariosLiga` is defined in another scope, you will need to ensure it is accessible in the scope where you're calling eval.

**Comment by Gimenez20** [comment]
If i want to edit the variables, what kind of command must i use it? same eval?
