### ISSUE TITLE
using proxy ip/overcoming ip limitations

### ISSUE THREAD

**Issue by jakjus** [mertushka/haxball.js#9]
hey mertushka,
as you know, there is limitation of 2 rooms per ip.

i'm running 9 rooms now and I use proxy ip's assigned to browser (old style using selenium) and I run 2 rooms per ip.

i'm wordering, how can i achieve running more than 2 rooms with haxball.js?

is IP discovered during webrtc connection init? 
maybe there is a way to spoof the IP in headless script so that we can overcome this restriction? or at least make a way for webrtc to use proxy IP?

**Comment by mertushka** [comment]
I've done a lot of work on this, but I still have 3 thoughts that are not clear in my mind. I don't think Basro checks IP Addresses via WebRTC, it's a little bit weird. We eliminated 1 option, 2 left. Most likely basro is doing IP checks over Websocket because it's the most logical option. The last option is API requests, which still leaves question marks in my mind. Before the room opens, basro receives 3 requests from us where he can get the IP Address. First, it may create an ip-based token via /headlesstoken, but it's unlikely. Secondly, it gets geolocation information from the ip address with /geo [GET](https://github.com/mertushka/haxball.js/blob/200ece8782d414ff6e5663be63454085bc72537a/src/index.js#L1877) (HBInit:geo). Third and lastly, it checks with /token [POST](https://github.com/mertushka/haxball.js/blob/200ece8782d414ff6e5663be63454085bc72537a/src/index.js#L1848)  whether the token is correct. My advice to you is to proxy for both the node-fetch (API Requests) and the ws module (Websocket Connection). A little challenging, but possible. I'll take a look when I get home.

**Comment by jakjus** [comment]
Great insight! I'll try my luck and I'll keep you updated.

**Comment by jakjus** [comment]
I made a mistake previously - Proxying WebSockets works 🎉 
I'm thinking about the way to fake it, but idk if I'll come up with one.

**Comment by mertushka** [comment]
> I'm thinking about the way to fake it, but idk if I'll come up with one.

Is it good idea to do it in open source project like this? There will be so many abusers that I can't imagine.

**Comment by jakjus** [comment]
You're right, I've edited my comment not to urge anyone.
